apiVersion: v1
kind: PersistentVolume
metadata:
  name: buddhi
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://ap-southeast-1b/vol-0b7899d0aa540d7d7
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-retain
  volumeMode: Filesystem
