apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: asvignesh
  name: buddhipvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-retain
  volumeMode: Filesystem
  volumeName: buddhi
